server.port=8090

# AllStak SDK Configuration — Real Backend
allstak.api-key=ask_live_iejcn9bsdss7b44p6if6wumwx0kd4brp
allstak.environment=development
allstak.release=v1.0.0-java-e2e
allstak.debug=true
allstak.service-name=java-sdk-e2e-test
allstak.flush-interval-ms=1000
allstak.buffer-size=100
allstak.capture-http-requests=true
allstak.capture-exceptions=true

# H2 Database Configuration
spring.datasource.url=jdbc:h2:mem:ordersdb
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
