package dev.allstak.database;

import dev.allstak.AllStakClient;
import dev.allstak.model.DatabaseQueryItem;

import java.sql.*;

/**
 * Statement wrapper that captures query telemetry for plain SQL statements.
 * Intercepts execute, executeQuery, and executeUpdate to record timing.
 */
class InstrumentedStatement implements Statement {

    protected final Statement delegate;
    protected final AllStakClient client;
    protected final String databaseType;
    protected final String databaseName;

    InstrumentedStatement(Statement delegate, AllStakClient client, String databaseType, String databaseName) {
        this.delegate = delegate;
        this.client = client;
        this.databaseType = databaseType;
        this.databaseName = databaseName;
    }

    // ---- Instrumented execute methods ----

    @Override
    public ResultSet executeQuery(String sql) throws SQLException {
        long start = System.currentTimeMillis();
        try {
            ResultSet rs = delegate.executeQuery(sql);
            captureQuery(sql, System.currentTimeMillis() - start, "success", null, -1);
            return rs;
        } catch (SQLException e) {
            captureQuery(sql, System.currentTimeMillis() - start, "error", e.getMessage(), 0);
            throw e;
        }
    }

    @Override
    public int executeUpdate(String sql) throws SQLException {
        long start = System.currentTimeMillis();
        try {
            int rows = delegate.executeUpdate(sql);
            captureQuery(sql, System.currentTimeMillis() - start, "success", null, rows);
            return rows;
        } catch (SQLException e) {
            captureQuery(sql, System.currentTimeMillis() - start, "error", e.getMessage(), 0);
            throw e;
        }
    }

    @Override
    public boolean execute(String sql) throws SQLException {
        long start = System.currentTimeMillis();
        try {
            boolean result = delegate.execute(sql);
            captureQuery(sql, System.currentTimeMillis() - start, "success", null, -1);
            return result;
        } catch (SQLException e) {
            captureQuery(sql, System.currentTimeMillis() - start, "error", e.getMessage(), 0);
            throw e;
        }
    }

    @Override
    public int executeUpdate(String sql, int autoGeneratedKeys) throws SQLException {
        long start = System.currentTimeMillis();
        try {
            int rows = delegate.executeUpdate(sql, autoGeneratedKeys);
            captureQuery(sql, System.currentTimeMillis() - start, "success", null, rows);
            return rows;
        } catch (SQLException e) {
            captureQuery(sql, System.currentTimeMillis() - start, "error", e.getMessage(), 0);
            throw e;
        }
    }

    @Override
    public int executeUpdate(String sql, int[] columnIndexes) throws SQLException {
        long start = System.currentTimeMillis();
        try {
            int rows = delegate.executeUpdate(sql, columnIndexes);
            captureQuery(sql, System.currentTimeMillis() - start, "success", null, rows);
            return rows;
        } catch (SQLException e) {
            captureQuery(sql, System.currentTimeMillis() - start, "error", e.getMessage(), 0);
            throw e;
        }
    }

    @Override
    public int executeUpdate(String sql, String[] columnNames) throws SQLException {
        long start = System.currentTimeMillis();
        try {
            int rows = delegate.executeUpdate(sql, columnNames);
            captureQuery(sql, System.currentTimeMillis() - start, "success", null, rows);
            return rows;
        } catch (SQLException e) {
            captureQuery(sql, System.currentTimeMillis() - start, "error", e.getMessage(), 0);
            throw e;
        }
    }

    @Override
    public boolean execute(String sql, int autoGeneratedKeys) throws SQLException {
        long start = System.currentTimeMillis();
        try {
            boolean result = delegate.execute(sql, autoGeneratedKeys);
            captureQuery(sql, System.currentTimeMillis() - start, "success", null, -1);
            return result;
        } catch (SQLException e) {
            captureQuery(sql, System.currentTimeMillis() - start, "error", e.getMessage(), 0);
            throw e;
        }
    }

    @Override
    public boolean execute(String sql, int[] columnIndexes) throws SQLException {
        long start = System.currentTimeMillis();
        try {
            boolean result = delegate.execute(sql, columnIndexes);
            captureQuery(sql, System.currentTimeMillis() - start, "success", null, -1);
            return result;
        } catch (SQLException e) {
            captureQuery(sql, System.currentTimeMillis() - start, "error", e.getMessage(), 0);
            throw e;
        }
    }

    @Override
    public boolean execute(String sql, String[] columnNames) throws SQLException {
        long start = System.currentTimeMillis();
        try {
            boolean result = delegate.execute(sql, columnNames);
            captureQuery(sql, System.currentTimeMillis() - start, "success", null, -1);
            return result;
        } catch (SQLException e) {
            captureQuery(sql, System.currentTimeMillis() - start, "error", e.getMessage(), 0);
            throw e;
        }
    }

    protected void captureQuery(String sql, long durationMs, String status, String errorMessage, int rowsAffected) {
        try {
            // Get trace context for correlation
            String traceId = "";
            String spanId = "";
            try {
                var reqCtx = AllStakClient.getRequestContext();
                if (reqCtx != null) {
                    traceId = reqCtx.getTraceId() != null ? reqCtx.getTraceId() : "";
                    // Generate a span ID for this DB query
                    spanId = java.util.UUID.randomUUID().toString().replace("-", "").substring(0, 16);
                }
            } catch (Exception ignored) {}

            String normalized = SqlNormalizer.normalize(sql);
            client.captureDbQuery(DatabaseQueryItem.builder()
                    .normalizedQuery(normalized)
                    .queryHash(SqlNormalizer.hash(normalized))
                    .queryType(SqlNormalizer.detectQueryType(sql))
                    .durationMs(durationMs)
                    .status(status)
                    .errorMessage(errorMessage)
                    .databaseName(databaseName)
                    .databaseType(databaseType)
                    .traceId(traceId)
                    .spanId(spanId)
                    .rowsAffected(rowsAffected)
                    .build());
        } catch (Exception ignored) {
            // Never let telemetry break application code
        }
    }

    // ---- Pure delegation ----

    @Override public void close() throws SQLException { delegate.close(); }
    @Override public int getMaxFieldSize() throws SQLException { return delegate.getMaxFieldSize(); }
    @Override public void setMaxFieldSize(int max) throws SQLException { delegate.setMaxFieldSize(max); }
    @Override public int getMaxRows() throws SQLException { return delegate.getMaxRows(); }
    @Override public void setMaxRows(int max) throws SQLException { delegate.setMaxRows(max); }
    @Override public void setEscapeProcessing(boolean enable) throws SQLException { delegate.setEscapeProcessing(enable); }
    @Override public int getQueryTimeout() throws SQLException { return delegate.getQueryTimeout(); }
    @Override public void setQueryTimeout(int seconds) throws SQLException { delegate.setQueryTimeout(seconds); }
    @Override public void cancel() throws SQLException { delegate.cancel(); }
    @Override public SQLWarning getWarnings() throws SQLException { return delegate.getWarnings(); }
    @Override public void clearWarnings() throws SQLException { delegate.clearWarnings(); }
    @Override public void setCursorName(String name) throws SQLException { delegate.setCursorName(name); }
    @Override public ResultSet getResultSet() throws SQLException { return delegate.getResultSet(); }
    @Override public int getUpdateCount() throws SQLException { return delegate.getUpdateCount(); }
    @Override public boolean getMoreResults() throws SQLException { return delegate.getMoreResults(); }
    @Override public boolean getMoreResults(int current) throws SQLException { return delegate.getMoreResults(current); }
    @Override public void setFetchDirection(int direction) throws SQLException { delegate.setFetchDirection(direction); }
    @Override public int getFetchDirection() throws SQLException { return delegate.getFetchDirection(); }
    @Override public void setFetchSize(int rows) throws SQLException { delegate.setFetchSize(rows); }
    @Override public int getFetchSize() throws SQLException { return delegate.getFetchSize(); }
    @Override public int getResultSetConcurrency() throws SQLException { return delegate.getResultSetConcurrency(); }
    @Override public int getResultSetType() throws SQLException { return delegate.getResultSetType(); }
    @Override public void addBatch(String sql) throws SQLException { delegate.addBatch(sql); }
    @Override public void clearBatch() throws SQLException { delegate.clearBatch(); }
    @Override public int[] executeBatch() throws SQLException { return delegate.executeBatch(); }
    @Override public Connection getConnection() throws SQLException { return delegate.getConnection(); }
    @Override public ResultSet getGeneratedKeys() throws SQLException { return delegate.getGeneratedKeys(); }
    @Override public int getResultSetHoldability() throws SQLException { return delegate.getResultSetHoldability(); }
    @Override public boolean isClosed() throws SQLException { return delegate.isClosed(); }
    @Override public void setPoolable(boolean poolable) throws SQLException { delegate.setPoolable(poolable); }
    @Override public boolean isPoolable() throws SQLException { return delegate.isPoolable(); }
    @Override public void closeOnCompletion() throws SQLException { delegate.closeOnCompletion(); }
    @Override public boolean isCloseOnCompletion() throws SQLException { return delegate.isCloseOnCompletion(); }
    @Override public <T> T unwrap(Class<T> iface) throws SQLException { return delegate.unwrap(iface); }
    @Override public boolean isWrapperFor(Class<?> iface) throws SQLException { return delegate.isWrapperFor(iface); }
}
