package dev.allstak.spring;

import ch.qos.logback.classic.spi.ILoggingEvent;
import ch.qos.logback.classic.spi.IThrowableProxy;
import ch.qos.logback.classic.spi.StackTraceElementProxy;
import ch.qos.logback.core.AppenderBase;
import dev.allstak.AllStak;
import dev.allstak.AllStakClient;

import java.util.Map;

/**
 * Logback appender that sends log events to AllStak.
 * Auto-configured by AllStakAutoConfiguration.
 */
public class AllStakLogbackAppender extends AppenderBase<ILoggingEvent> {

    private static final ThreadLocal<Boolean> SENDING = ThreadLocal.withInitial(() -> false);

    @Override
    protected void append(ILoggingEvent event) {
        // Prevent infinite loop: don't capture logs generated by AllStak SDK itself
        if (SENDING.get()) return;

        String loggerName = event.getLoggerName();
        if (loggerName != null && (loggerName.startsWith("dev.allstak") || loggerName.contains("AllStak"))) {
            return;
        }

        AllStakClient client = AllStak.getClient();
        if (client == null) return;

        SENDING.set(true);
        try {
            String level = mapLevel(event.getLevel().toString());
            String message = event.getFormattedMessage();

            // Skip SDK internal debug messages
            if (message != null && message.startsWith("[AllStak SDK")) return;

            // Include stack trace in message if present
            IThrowableProxy tp = event.getThrowableProxy();
            if (tp != null) {
                StringBuilder sb = new StringBuilder(message);
                sb.append("\n").append(tp.getClassName()).append(": ").append(tp.getMessage());
                for (StackTraceElementProxy step : tp.getStackTraceElementProxyArray()) {
                    sb.append("\n  at ").append(step.toString());
                    if (sb.length() > 4000) break;
                }
                message = sb.toString();
            }

            // Get trace_id from MDC
            String traceId = event.getMDCPropertyMap().get("traceId");
            if (traceId == null) {
                var reqCtx = AllStakClient.getRequestContext();
                if (reqCtx != null) traceId = reqCtx.getTraceId();
            }

            // Get service from MDC or config
            String service = event.getMDCPropertyMap().get("service");

            Map<String, Object> metadata = null;
            if (!event.getMDCPropertyMap().isEmpty()) {
                metadata = new java.util.HashMap<>(event.getMDCPropertyMap());
                metadata.remove("traceId"); // already a top-level field
                metadata.remove("service");
                if (metadata.isEmpty()) metadata = null;
            }

            client.captureLog(level, message, service, traceId, null, null, null, null, null, metadata);
        } catch (Exception e) {
            // Never break the app
        } finally {
            SENDING.set(false);
        }
    }

    private String mapLevel(String level) {
        return switch (level.toUpperCase()) {
            case "TRACE", "ALL" -> "debug";
            case "DEBUG" -> "debug";
            case "INFO" -> "info";
            case "WARN" -> "warn";
            case "ERROR" -> "error";
            default -> "info";
        };
    }
}
